name: 'gitversion-helper'
description: 'adds short sha to prerelease tags'
inputs:
  semver:
    required: true
  shortsha:
    required: true
  useTagIfExists:
    default: false
  githubRef:
    default: ""
  preReleaseNumber:
    default: ""
outputs:
  semver:
    description: 'calculated semver'
  isrelease:
    description: boolean, true if current version is a "release" version, false if not
  pythoncompatibleversion:
    description: hopefully a python compatible version
runs:
  using: 'node12'
  main: 'dist/index.js'
