name: 'gitversion-helper'
description: 'Adds short SHA to prerelease tags'
inputs:
  semver:
    required: true
    description: todo
  shortsha:
    required: true
    description: todo
  useTagIfExists:
    default: "false"
    description: Use version from git tag if one exists
  preReleaseNumber:
    default: ""
    description: todo
  simplePRversion:
    default: "false"
    description: 'Return version in form of pr-{prnumber}-{shortSHA}'
  githubToken:
    default: ''
    description: GitHub token - required if simplePRversion is true
outputs:
  semver:
    description: 'calculated semver'
  isrelease:
    description: boolean, true if current version is a "release" version, false if not
  pythoncompatibleversion:
    description: hopefully a python compatible version
runs:
  using: 'node20'
  main: 'dist/index.js'
